# Generated by Django 4.1.7 on 2023-04-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_about_social_imageabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
