# Generated by Django 4.1.7 on 2023-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_about_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
